name: dbtech_tdd_clean_archecture_bloc
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  # Core
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Data Handling
  dartz: ^0.10.1
  equatable: ^2.0.5

  flutter:
    sdk: flutter

  # File Handling
  file_picker: ^6.1.1
  open_file: ^3.3.2
  path_provider: ^2.1.1

  # Internationalization
  intl: ^0.18.1

  # Preferences and Data Storage
  shared_preferences: ^2.2.2

  # State Management and Dependency Injection
  get_it: ^7.6.4
  provider: ^6.1.1

  # UI Elements
  chewie: ^1.7.4
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  iconly: ^1.0.1
  image_picker: ^1.0.5
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  video_thumbnail: ^0.5.3

  # External Interactions
  url_launcher: ^6.2.2
  youtube_metadata: ^1.0.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  firebase_ui_auth: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  mocktail: ^1.0.2
  mockito: ^5.4.4
  very_good_analysis: ^5.1.0
  fake_cloud_firestore: ^2.4.5
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
