name: dbtech_tdd_clean_archecture_bloc
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # Provides iOS-style icons
  go_router: ^13.0.0 # Powerful and flexible router for Flutter apps
  google_fonts: ^6.1.0 # Access a vast collection of Google Fonts
  hive: ^2.2.3 # Lightweight and fast key-value database for Flutter
  equatable: ^2.0.5 # Helps with value-based comparison of objects
  hive_flutter: ^1.1.0 # Widgets for integrating Hive with Flutter UI
  get_it: ^7.6.4 # Dependency injection (DI) framework for accessing objects
  path_provider: ^2.1.1 # Finds commonly used paths on the device's file system
  dartz: ^0.10.1 # Functional programming utilities for Dart
  flutter_bloc: ^8.1.3 # State management library for building reactive apps
  freezed_annotation: ^2.4.1 # Code generation for immutable classes
  json_annotation: ^4.8.1 # Code generation for serialization/deserialization
  cached_network_image: ^3.3.0 # Efficiently caches images from the network

dev_dependencies:
  flutter_test:
    sdk: flutter # Testing framework for Flutter apps
  flutter_lints: ^3.0.1 # Lint rules for ensuring code quality
  build_runner: ^2.4.7 # Used for code generation with freezed and json_serializable
  freezed: ^2.4.6 # Code generation for immutable classes (runtime part)
  json_serializable: ^6.7.1 # Code generation for serialization/deserialization
  analyzer: ^6.2.0 # Static analysis for Dart code

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
